#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org


START=98

start() {
	ubus -S list network.interface.guest 2>/dev/null ||{
		echo "Interface guest not found"
		exit
	}
	ubus call network.interface down "{ \"interface\" : \"wan\" }"
	ubus call network.interface up "{ \"interface\" : \"wan\" }"
}

stop(){
	exit;
}