#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

SERVICE_USE_PID=1

START=50

start() {
	uci del system.@system[0].guitokenid
	uci commit system
	[ -d /var/log/lighttpd ] || mkdir -p /var/log/lighttpd
	chmod 0777 /var/log/lighttpd
	/usr/sbin/lighttpd -f /etc/lighttpd/lighttpd_firewall.conf&
	service_start /usr/sbin/lighttpd -f /etc/lighttpd/lighttpd.conf

}

stop() {
	service_stop /usr/sbin/lighttpd
}

