USER_DEPTH = .

include $(USER_DEPTH)/config/makeinclude/platform.make

USER_SUB_DIRS = \
				${USER_DEPTH}/QtkeyMangent \
				${USER_DEPTH}/QtKeyEncrypt \
#				${USER_DEPTH}/QtKeyDistribute

include $(USER_DEPTH)/config/makeinclude/all_in_one.make
