$(eval $(call PackageDir,qca-ieee1905-security-config_libieee1905,qca-ieee1905-security-config/libieee1905,))
$(eval $(call PackageDir,qca-ieee1905-security-config_libstorage,qca-ieee1905-security-config/libstorage,))
$(eval $(call PackageDir,qca-ieee1905-security-config_libwpa2,qca-ieee1905-security-config/libwpa2,))
$(eval $(call PackageDir,qca-ieee1905-security-config_qca-ieee1905-init,qca-ieee1905-security-config/qca-ieee1905-init,))
$(eval $(call PackageDir,qca-ieee1905-security-config_qca-wsplcd,qca-ieee1905-security-config/qca-wsplcd,))
$(eval $(call PackageDir,qca-wsplc-luci,qca-wsplc-luci,))
